// Generated code

#if !DEBUG
#include "Shaders/ShaderProvider/ShaderProvider.h"
const string ShaderProvider::UnpackCode(const uint32_t& h) {
switch (h) {
case 1939412094: return "#version 460 core\nin vec2 fragmentTextureCoords;uniform sampler2D dataTexture;out vec4 color;void main(){color=texture(dataTexture,fragmentTextureCoords);}";
case 776390504: return "#version 460 core\nin vec4 position;in vec2 vertexTextureCoords;out vec2 fragmentTextureCoords;void main(){gl_Position=position;fragmentTextureCoords=vertexTextureCoords;}";
case 3759396228: return "#version 460 core\nlayout(local_size_x=16,local_size_y=16,local_size_z=1)in;uniform ivec2 size;restrict writeonly uniform image2D texture;layout(std430)restrict readonly buffer cellsBuffer{uint Cells[];};void main(){ivec2 b=ivec2(gl_GlobalInvocationID.xy);if(b.x>=size.x||b.y>=size.y)return;uint c=b.y*size.x+b.x;float d=float(Cells[c])*.5;imageStore(texture,b,vec4(d,d,d,1.));}";
case 1549598707: return "#version 460 core\nlayout(local_size_x=16,local_size_y=16,local_size_z=1)in;uniform ivec2 size;uniform ivec2 lastPosition;uniform ivec2 currentPosition;uniform bool edgeLoop;uniform bool drawing;layout(std430)restrict writeonly buffer cellsBuffer{uint Cells[];};float b(vec2 f,vec2 g,vec2 h){vec2 j=h-f;vec2 k=g-f;float l=clamp(dot(j,k)/dot(k,k),0,1);return length(j-k*l);}void c(ivec2 m,ivec2 n,ivec2 p){if(b(m,n,p)<.5)Cells[p.y*size.x+p.x]=drawing?1:0;}void d(ivec2 q){for(int y=-1;y<2;y++){for(int x=-1;x<2;x++){ivec2 r=ivec2(x,y)*size;ivec2 s=lastPosition+r;ivec2 t=currentPosition+r;c(s,t,q);}}}void main(){ivec2 v=ivec2(gl_GlobalInvocationID.xy);if(v.x>=size.x||v.y>=size.y)return;if(edgeLoop){d(v);}else{c(lastPosition,currentPosition,v);}}";
case 1060733367: return "#version 460 core\nlayout(local_size_x=16,local_size_y=16,local_size_z=1)in;uniform ivec2 size;uniform uint seed;layout(std430)restrict writeonly buffer cellsBuffer{uint Cells[];};uint b(uint c){c^=2747636419;c*=2654435769;c^=c>>16;c*=seed+1;c*=2654435769;c^=c>>16;c*=2654435769;return c;}void main(){ivec2 d=ivec2(gl_GlobalInvocationID.xy);if(d.x>=size.x||d.y>=size.y)return;uint f=d.y*size.x+d.x;Cells[f]=b(f)%2;}";
case 3453390440: return "#version 460 core\nlayout(local_size_x=16,local_size_y=16,local_size_z=1)in;uniform ivec2 size;uniform bool edgeLoop;uniform int birthRules;uniform int survivalRules;layout(std430)restrict readonly buffer inputBuffer{uint Inputs[];};layout(std430)restrict writeonly buffer outputBuffer{uint Outputs[];};int b(int f,int g){if(edgeLoop){if(f<0)f=size.x-1;else if(f>=size.x)f=0;if(g<0)g=size.y-1;else if(g>=size.y)g=0;}else if(f<0||f>=size.x||g<0||g>=size.y){return-1;}return g*size.x+f;}uint c(ivec2 h,uint j){uint k=0;for(int y=-1;y<2;y++){for(int x=-1;x<2;x++){int l=b(h.x+x,h.y+y);if(l!=-1&&l!=j)k+=Inputs[l];}}return k;}bool d(ivec2 m,uint n){uint p=c(m,n);int q=bool(Inputs[n])?survivalRules:birthRules;return bool((1<<p)&q);}void main(){ivec2 r=ivec2(gl_GlobalInvocationID.xy);if(r.x>=size.x||r.y>=size.y)return;uint s=r.y*size.x+r.x;Outputs[s]=uint(d(r,s));}";
default: return ""; }}
#endif
